import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../services/api';

export default function AdminModeration() {
  const [queue, setQueue] = useState({ tasks: [], classes: [], reports: [] }); const [error, setError] = useState('');
  async function load() { try { const { data } = await api.get('/admin/moderation'); setQueue(data.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Admin access is required.'); } }
  useEffect(() => { load(); }, []);
  async function moderate(type, id, decision) { try { await api.patch(`/admin/${type}/${id}/moderate`, { decision }); toast.success(`${type === 'tasks' ? 'Task' : 'Class'} ${decision}d.`); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to update moderation status.'); } }
  if (error) return <section><h1 className="text-3xl font-bold">Admin moderation</h1><p className="mt-6 text-red-700">{error}</p></section>;
  return <section><h1 className="text-3xl font-bold">Admin moderation</h1><p className="mt-2 text-slate-600">Review submitted tasks, classes, and community reports.</p><ModerationList title="Pending tasks" items={queue.tasks} type="tasks" onModerate={moderate} render={(item) => <><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500">By {item.requester?.name} · {item.category}</p><p className="mt-2 text-sm text-slate-700">{item.description}</p></>} /><ModerationList title="Pending classes" items={queue.classes} type="classes" onModerate={moderate} render={(item) => <><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500">By {item.instructor?.name} · {item.category}</p><p className="mt-2 text-sm text-slate-700">{item.description}</p></>} /><section className="mt-8"><h2 className="text-xl font-bold">Open reports</h2><div className="mt-3 rounded-xl bg-white shadow-sm">{queue.reports.length ? queue.reports.map((report) => <div key={report._id} className="border-b border-slate-100 p-4 last:border-0"><p className="font-semibold">{report.targetType} report · {report.reason}</p><p className="mt-1 text-sm text-slate-600">{report.details || 'No additional details.'}</p></div>) : <p className="p-4 text-slate-600">No open reports.</p>}</div></section></section>;
}

function ModerationList({ title, items, type, onModerate, render }) { return <section className="mt-8"><h2 className="text-xl font-bold">{title}</h2><div className="mt-3 rounded-xl bg-white shadow-sm">{items.length ? items.map((item) => <article key={item._id} className="border-b border-slate-100 p-4 last:border-0"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl">{render(item)}</div><div className="flex gap-2"><button onClick={() => onModerate(type, item._id, 'reject')} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600">Reject</button><button onClick={() => onModerate(type, item._id, 'approve')} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Approve</button></div></div></article>) : <p className="p-4 text-slate-600">Nothing is waiting for review.</p>}</div></section>; }
