import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';

export default function CreateClass() {
  const navigate = useNavigate(); const [saving, setSaving] = useState(false); const input = 'mt-1 w-full rounded-lg border border-slate-300 px-3 py-2';
  async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const { data } = await api.post('/classes', Object.fromEntries(form)); if (form.get('submitForApproval')) await api.post(`/classes/${data.data.class._id}/submit`); toast.success(form.get('submitForApproval') ? 'Class submitted for approval.' : 'Class saved as a draft.'); navigate('/dashboard/classes'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to create class.'); } finally { setSaving(false); } }
  return <section className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-3xl font-bold">Create a class</h1><p className="mt-2 text-slate-600">New classes are reviewed before they are published.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-xl bg-white p-6 shadow-sm"><label className="block font-medium">Title<input required name="title" minLength="5" className={input} /></label><label className="block font-medium">Description<textarea required name="description" minLength="20" rows="5" className={input} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Category<input required name="category" className={input} placeholder="Education" /></label><label className="block font-medium">Skills<input name="skills" className={input} placeholder="React, JavaScript" /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Date<input required name="date" type="date" className={input} /></label><label className="block font-medium">Capacity<input required name="capacity" type="number" min="1" className={input} /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Start time<input required name="startTime" type="time" className={input} /></label><label className="block font-medium">End time<input required name="endTime" type="time" className={input} /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Price (₹)<input name="price" type="number" min="0" defaultValue="0" className={input} /></label><label className="block font-medium">Location type<select required name="locationType" defaultValue="online" className={input}><option value="online">Online</option><option value="offline">Offline</option><option value="hybrid">Hybrid</option></select></label></div><label className="block font-medium">Location or meeting link<input name="location" className={input} /></label><label className="block font-medium">Requirements<textarea name="requirements" rows="3" className={input} /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="submitForApproval" /> Submit for approval now</label><button disabled={saving} className="rounded-lg bg-indigo-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save class'}</button></form></section>;
}
