import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';

const categories = ['Programming', 'Design', 'Education', 'Home Services', 'Repairs', 'Driving', 'Photography', 'Video', 'Marketing', 'Writing', 'Music', 'Fitness', 'Consulting', 'Other'];
export default function CreateTask() {
  const navigate = useNavigate(); const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { const { data } = await api.post('/tasks', Object.fromEntries(form)); if (form.get('submitForApproval')) await api.post(`/tasks/${data.data.task._id}/submit`); toast.success(form.get('submitForApproval') ? 'Task submitted for approval.' : 'Task saved as a draft.'); navigate('/dashboard/tasks'); } catch (error) { toast.error(error.response?.data?.message || error.message); } finally { setSaving(false); } }
  const input = 'mt-1 w-full rounded-lg border border-slate-300 px-3 py-2';
  return <section className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-3xl font-bold">Post a service request</h1><p className="mt-2 text-slate-600">Describe what you need. Submitted tasks are reviewed before becoming public.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-xl bg-white p-6 shadow-sm"><label className="block font-medium">Title<input required name="title" minLength="5" className={input} placeholder="Need a React developer for a small website" /></label><label className="block font-medium">Description<textarea required name="description" minLength="20" rows="5" className={input} placeholder="Explain the work, outcome, and expectations." /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Category<select required name="category" className={input}><option value="">Choose one</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="block font-medium">Work mode<select required name="workMode" defaultValue="online" className={input}><option value="online">Online</option><option value="offline">Offline</option><option value="hybrid">Hybrid</option></select></label></div><label className="block font-medium">Required skills<input name="requiredSkills" className={input} placeholder="React, JavaScript, CSS" /><span className="mt-1 block text-xs font-normal text-slate-500">Separate skills with commas.</span></label><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Minimum budget (₹)<input name="budgetMin" type="number" min="0" className={input} /></label><label className="block font-medium">Maximum budget (₹)<input name="budgetMax" type="number" min="0" className={input} /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">Duration<input name="durationValue" type="number" min="1" className={input} /></label><label className="block font-medium">Duration unit<select name="durationUnit" className={input}><option value="days">Days</option><option value="hours">Hours</option><option value="weeks">Weeks</option><option value="months">Months</option></select></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="block font-medium">City<input name="locationCity" className={input} /></label><label className="block font-medium">Deadline<input name="deadline" type="date" className={input} /></label></div><label className="block font-medium">Additional requirements<textarea name="additionalRequirements" rows="3" className={input} /></label><label className="flex items-center gap-2 text-sm"><input name="submitForApproval" type="checkbox" /> Submit for admin approval now</label><button disabled={saving} className="rounded-lg bg-indigo-600 px-5 py-2 font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save task'}</button></form></section>;
}
