import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function TaskDetail() {
  const { taskId } = useParams(); const { user } = useAuth(); const [task, setTask] = useState(null); const [error, setError] = useState(''); const [applying, setApplying] = useState(false);
  useEffect(() => { api.get(`/tasks/${taskId}`).then(({ data }) => setTask(data.data.task)).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load task.')); }, [taskId]);
  async function apply(event) { event.preventDefault(); setApplying(true); try { const form = new FormData(event.currentTarget); await api.post(`/applications/tasks/${taskId}`, Object.fromEntries(form)); toast.success('Application sent to the requester.'); event.currentTarget.reset(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to submit application.'); } finally { setApplying(false); } }
  if (error) return <section className="mx-auto max-w-3xl px-4 py-12"><p className="text-red-700">{error}</p><Link className="mt-4 inline-block text-indigo-600" to="/tasks">Back to tasks</Link></section>;
  if (!task) return <main className="p-12 text-center">Loading task…</main>;
  return <section className="mx-auto max-w-3xl px-4 py-12"><p className="font-semibold text-indigo-600">{task.category}</p><h1 className="mt-2 text-4xl font-bold">{task.title}</h1><div className="mt-6 rounded-xl bg-white p-6 shadow-sm"><p className="whitespace-pre-wrap text-slate-700">{task.description}</p><dl className="mt-6 grid gap-4 border-t pt-6 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Budget</dt><dd className="font-semibold">₹{task.budget?.min ?? 0}{task.budget?.max ? ` – ₹${task.budget.max}` : '+'}</dd></div><div><dt className="text-sm text-slate-500">Work mode</dt><dd className="font-semibold capitalize">{task.workMode}</dd></div><div><dt className="text-sm text-slate-500">Requester</dt><dd className="font-semibold">{task.requester?.name}</dd></div><div><dt className="text-sm text-slate-500">Location</dt><dd className="font-semibold">{task.location?.city || 'Remote'}</dd></div></dl><div className="mt-6 flex flex-wrap gap-2">{task.requiredSkills?.map((skill) => <span key={skill} className="rounded bg-slate-100 px-3 py-1 text-sm">{skill}</span>)}</div></div>{user && <form onSubmit={apply} className="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Apply to this task</h2><p className="mt-1 text-sm text-slate-600">Introduce yourself and propose your terms.</p><textarea required name="pitch" minLength="20" rows="5" className="mt-4 w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Explain why you are a good fit…" /><div className="mt-4 grid gap-4 sm:grid-cols-2"><input name="proposedPrice" type="number" min="0" placeholder="Proposed price (₹)" className="rounded-lg border border-slate-300 px-3 py-2" /><input name="proposedDuration" type="number" min="1" placeholder="Duration" className="rounded-lg border border-slate-300 px-3 py-2" /></div><button disabled={applying} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white disabled:opacity-50">{applying ? 'Sending…' : 'Send application'}</button></form>}{!user && <p className="mt-6 rounded-xl bg-indigo-50 p-4 text-indigo-900"><Link className="font-semibold underline" to="/login">Log in</Link> to apply for this task.</p>}</section>;
}
