import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';

export default function TaskProgress() {
  const { taskId } = useParams(); const [task, setTask] = useState(null); const [profile, setProfile] = useState(null); const [reviews, setReviews] = useState([]); const [error, setError] = useState('');
  async function load() { try { const [taskResponse, profileResponse, reviewsResponse] = await Promise.all([api.get(`/tasks/${taskId}`), api.get('/auth/me'), api.get(`/reviews/tasks/${taskId}`)]); setTask(taskResponse.data.data.task); setProfile(profileResponse.data.data.user); setReviews(reviewsResponse.data.data.reviews); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load task progress.'); } }
  useEffect(() => { load(); }, [taskId]);
  async function requestCompletion() { try { await api.post(`/completions/tasks/${taskId}/request`); toast.success('Completion request sent to the requester.'); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to request completion.'); } }
  async function confirmCompletion() { try { await api.post(`/completions/tasks/${taskId}/confirm`); toast.success('Task completed. You can now review each other.'); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to confirm completion.'); } }
  async function submitReview(event) { event.preventDefault(); try { const form = new FormData(event.currentTarget); await api.post(`/reviews/tasks/${taskId}`, Object.fromEntries(form)); toast.success('Review submitted.'); event.currentTarget.reset(); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to submit review.'); } }
  if (error) return <p className="text-red-700">{error}</p>; if (!task || !profile) return <p className="text-slate-600">Loading task progress…</p>;
  const isRequester = String(task.requester?._id || task.requester) === String(profile.id); const isProvider = String(task.selectedProvider) === String(profile.id); const completionRequested = Boolean(task.completion?.providerRequestedAt); const canReview = task.status === 'completed' && !reviews.some((review) => String(review.reviewer?._id || review.reviewer) === String(profile.id));
  return <section className="mx-auto max-w-3xl"><Link className="text-sm font-semibold text-indigo-600" to={isRequester ? '/dashboard/tasks' : '/dashboard/applications'}>← Back</Link><h1 className="mt-3 text-3xl font-bold">{task.title}</h1><p className="mt-2 capitalize text-slate-600">Status: {task.status.replaceAll('_', ' ')}</p><div className="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Completion</h2>{task.status === 'in_progress' && isProvider && !completionRequested && <button onClick={requestCompletion} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Request completion</button>}{task.status === 'in_progress' && completionRequested && isRequester && <button onClick={confirmCompletion} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white">Confirm completed work</button>}{completionRequested && task.status === 'in_progress' && <p className="mt-3 text-sm text-amber-700">The provider requested completion. Waiting for requester confirmation.</p>}{task.status === 'completed' && <p className="mt-3 text-sm text-emerald-700">Completed on {new Date(task.completion?.completedAt).toLocaleDateString()}.</p>}</div>{canReview && <form onSubmit={submitReview} className="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Leave a review</h2><div className="mt-4 flex gap-3"><select required name="rating" defaultValue="" className="rounded-lg border border-slate-300 px-3 py-2"><option value="" disabled>Rating</option>{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} stars</option>)}</select><button className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Submit review</button></div><textarea name="comment" maxLength="3000" rows="3" placeholder="Share your experience (optional)" className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2" /></form>}<section className="mt-6 rounded-xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Reviews</h2>{reviews.length ? <div className="mt-4 space-y-4">{reviews.map((review) => <article key={review._id} className="border-t border-slate-100 pt-4"><p className="font-semibold">{review.reviewer?.name} · {review.rating}/5</p>{review.comment && <p className="mt-1 text-slate-600">{review.comment}</p>}</article>)}</div> : <p className="mt-3 text-sm text-slate-600">Reviews will appear once the work is completed.</p>}</section></section>;
}
