import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import TaskCard from '../components/TaskCard';

export default function Tasks() {
  const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filters, setFilters] = useState({ q: '', category: '', workMode: '' });
  async function loadTasks(event) { event?.preventDefault(); setLoading(true); setError(''); try { const { data } = await api.get('/tasks', { params: filters }); setTasks(data.data.tasks); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load tasks.'); } finally { setLoading(false); } }
  useEffect(() => { loadTasks(); }, []);
  return <section className="mx-auto max-w-6xl px-4 py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Browse tasks</h1><p className="mt-2 text-slate-600">Find service requests that suit your expertise.</p></div><Link className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white" to="/tasks/new">Post a task</Link></div><form onSubmit={loadTasks} className="mt-8 grid gap-3 rounded-xl bg-white p-4 shadow-sm sm:grid-cols-4"><input value={filters.q} onChange={(event) => setFilters({ ...filters, q: event.target.value })} placeholder="Search tasks" className="rounded-lg border border-slate-300 px-3 py-2" /><input value={filters.category} onChange={(event) => setFilters({ ...filters, category: event.target.value })} placeholder="Category" className="rounded-lg border border-slate-300 px-3 py-2" /><select value={filters.workMode} onChange={(event) => setFilters({ ...filters, workMode: event.target.value })} className="rounded-lg border border-slate-300 px-3 py-2"><option value="">Any work mode</option><option value="online">Online</option><option value="offline">Offline</option><option value="hybrid">Hybrid</option></select><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Search</button></form>{error && <p className="mt-6 rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}{loading ? <p className="mt-8 text-slate-600">Loading tasks…</p> : tasks.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{tasks.map((task) => <TaskCard key={task._id} task={task} />)}</div> : <div className="mt-8 rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-600">No published tasks match those filters yet.</div>}</section>;
}
