import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../services/api';

export default function TaskApplications() {
  const { taskId } = useParams(); const [task, setTask] = useState(null); const [applications, setApplications] = useState([]); const [error, setError] = useState('');
  async function load() { try { const { data } = await api.get(`/applications/tasks/${taskId}`); setTask(data.data.task); setApplications(data.data.applications); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load applicants.'); } }
  useEffect(() => { load(); }, [taskId]);
  async function decide(id, status) { try { await api.patch(`/applications/${id}/decision`, { status }); toast.success(status === 'accepted' ? 'Provider selected. Negotiation is next.' : `Application ${status}.`); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to update application.'); } }
  if (error) return <p className="text-red-700">{error}</p>;
  return <section><Link className="text-sm font-semibold text-indigo-600" to="/dashboard/tasks">← My tasks</Link><h1 className="mt-3 text-3xl font-bold">Applicants</h1><p className="mt-2 text-slate-600">{task?.title || 'Loading task…'}</p><div className="mt-6 space-y-4">{applications.map((application) => <article key={application._id} className="rounded-xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{application.applicant?.name}</h2><p className="text-sm text-slate-500">{application.applicant?.location?.city || 'Location not listed'} · ★ {application.applicant?.ratingAverage?.toFixed?.(1) || '0.0'}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{application.status}</span></div><p className="mt-4 whitespace-pre-wrap text-slate-700">{application.pitch}</p><p className="mt-4 text-sm"><strong>Proposal:</strong> {application.proposedPrice !== undefined ? `₹${application.proposedPrice}` : 'Price to discuss'}{application.proposedDuration?.value ? ` · ${application.proposedDuration.value} ${application.proposedDuration.unit}` : ''}</p>{['pending', 'shortlisted'].includes(application.status) && <div className="mt-5 flex gap-3"><button onClick={() => decide(application._id, 'shortlisted')} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Shortlist</button><button onClick={() => decide(application._id, 'rejected')} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-600">Reject</button><button onClick={() => decide(application._id, 'accepted')} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Accept provider</button></div>}</article>)}{!applications.length && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-slate-600">No applications yet.</p>}</div></section>;
}
