import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import morgan from 'morgan';
import { env } from './config/env.js';
import healthRouter from './routes/health.routes.js';
import authRouter from './routes/auth.routes.js';
import taskRouter from './routes/task.routes.js';
import applicationRouter from './routes/application.routes.js';
import conversationRouter from './routes/conversation.routes.js';
import termsRouter from './routes/terms.routes.js';
import paymentRouter from './routes/payment.routes.js';
import { handleRazorpayWebhook } from './controllers/payment.controller.js';
import completionRouter from './routes/completion.routes.js';
import reviewRouter from './routes/review.routes.js';
import classRouter from './routes/class.routes.js';
import notificationRouter from './routes/notification.routes.js';
import adminRouter from './routes/admin.routes.js';
import { notFound } from './middleware/notFound.js';
import { errorHandler } from './middleware/errorHandler.js';

const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ origin: env.clientUrl, credentials: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-7', legacyHeaders: false }));
app.post('/api/v1/payments/webhook', express.raw({ type: 'application/json' }), handleRazorpayWebhook);
app.use(express.json({ limit: '1mb' }));
if (env.nodeEnv !== 'test') app.use(morgan(env.nodeEnv === 'production' ? 'combined' : 'dev'));
app.use('/api/v1/health', healthRouter);
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/tasks', taskRouter);
app.use('/api/v1/applications', applicationRouter);
app.use('/api/v1/conversations', conversationRouter);
app.use('/api/v1/terms', termsRouter);
app.use('/api/v1/payments', paymentRouter);
app.use('/api/v1/completions', completionRouter);
app.use('/api/v1/reviews', reviewRouter);
app.use('/api/v1/classes', classRouter);
app.use('/api/v1/notifications', notificationRouter);
app.use('/api/v1/admin', adminRouter);
app.use(notFound);
app.use(errorHandler);
export default app;
