import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from '../services/api';
import { loadRazorpayCheckout } from '../services/razorpay';

export default function TermsPanel({ applicationId, userId }) {
  const [terms, setTerms] = useState(null); const [task, setTask] = useState(null); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [paying, setPaying] = useState(false);
  async function load() { try { const { data } = await api.get(`/terms/applications/${applicationId}`); setTerms(data.data.terms); setTask(data.data.task); } catch (error) { toast.error(error.response?.data?.message || 'Unable to load terms.'); } finally { setLoading(false); } }
  useEffect(() => { setLoading(true); setEditing(false); load(); }, [applicationId]);
  async function save(event) { event.preventDefault(); try { const { data } = await api.put(`/terms/applications/${applicationId}`, Object.fromEntries(new FormData(event.currentTarget))); setTerms(data.data.terms); setEditing(false); toast.success('Updated terms proposed. Both parties need to accept this version.'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to save terms.'); } }
  async function accept() { try { const { data } = await api.post(`/terms/applications/${applicationId}/accept`); setTerms(data.data.terms); setTask((current) => ({ ...current, status: data.data.bothAccepted ? 'payment_pending' : current.status })); toast.success(data.data.bothAccepted ? 'Terms accepted by both parties. Payment is ready.' : 'Your acceptance was recorded.'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to accept terms.'); } }
  async function pay() { try { setPaying(true); const [{ data: config }, { data: orderResponse }] = await Promise.all([api.get('/payments/config'), api.post(`/payments/applications/${applicationId}/order`)]); if (!config.data.configured) throw new Error('Razorpay is not configured on the server.'); await loadRazorpayCheckout(); const order = orderResponse.data.order; const checkout = new window.Razorpay({ key: config.data.keyId, amount: order.amount, currency: order.currency, name: 'Skill Exchange', description: task?.title || 'Service payment', order_id: order.id, handler: async (response) => { try { await api.post('/payments/verify', response); setTask((current) => ({ ...current, status: 'in_progress' })); toast.success('Payment verified. Work can begin.'); } catch (error) { toast.error(error.response?.data?.message || 'Payment could not be verified.'); } finally { setPaying(false); } }, modal: { ondismiss: () => setPaying(false) } }); checkout.open(); } catch (error) { setPaying(false); toast.error(error.response?.data?.message || error.message || 'Unable to start payment.'); } }
  if (loading) return <p className="p-4 text-sm text-slate-500">Loading terms…</p>;
  if (editing || !terms) return <form onSubmit={save} className="space-y-3 border-b border-slate-200 p-4"><div className="flex items-center justify-between"><p className="font-semibold">{terms ? 'Propose updated terms' : 'Propose terms'}</p>{terms && <button type="button" onClick={() => setEditing(false)} className="text-sm text-slate-600">Cancel</button>}</div><div className="grid gap-3 sm:grid-cols-2"><input required name="finalPrice" type="number" min="0" defaultValue={terms?.finalPrice} placeholder="Final price (₹)" className="rounded-lg border border-slate-300 px-3 py-2" /><input required name="durationValue" type="number" min="1" defaultValue={terms?.expectedDuration?.value} placeholder="Expected duration" className="rounded-lg border border-slate-300 px-3 py-2" /></div><div className="grid gap-3 sm:grid-cols-2"><select name="durationUnit" defaultValue={terms?.expectedDuration?.unit || 'days'} className="rounded-lg border border-slate-300 px-3 py-2"><option value="hours">Hours</option><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option></select><input name="deadline" type="date" defaultValue={terms?.deadline?.slice?.(0, 10)} className="rounded-lg border border-slate-300 px-3 py-2" /></div><textarea name="additionalNotes" defaultValue={terms?.additionalNotes} placeholder="Additional notes" rows="2" className="w-full rounded-lg border border-slate-300 px-3 py-2" /><button className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Propose terms</button></form>;
  const accepted = Boolean(terms.requesterAcceptedAt && terms.providerAcceptedAt);
  const requesterCanPay = accepted && task?.status === 'payment_pending' && String(task.requester) === String(userId);
  return <section className="border-b border-slate-200 bg-indigo-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-indigo-950">Current terms · Version {terms.version}</p><p className="mt-1 text-sm text-indigo-900">₹{terms.finalPrice} · {terms.expectedDuration.value} {terms.expectedDuration.unit}{terms.deadline ? ` · Deadline ${new Date(terms.deadline).toLocaleDateString()}` : ''}</p>{terms.additionalNotes && <p className="mt-1 text-sm text-indigo-900">{terms.additionalNotes}</p>}</div><div className="flex flex-wrap gap-2"><button onClick={() => setEditing(true)} disabled={accepted} className="rounded-lg border border-indigo-300 px-3 py-2 text-sm font-semibold text-indigo-800 disabled:opacity-50">Update</button><button onClick={accept} disabled={accepted} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{accepted ? 'Accepted by both' : 'Accept terms'}</button>{requesterCanPay && <button onClick={pay} disabled={paying} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{paying ? 'Opening payment…' : `Pay ₹${terms.finalPrice}`}</button>}</div></div><p className="mt-2 text-xs text-indigo-800">Requester: {terms.requesterAcceptedAt ? 'accepted' : 'awaiting'} · Provider: {terms.providerAcceptedAt ? 'accepted' : 'awaiting'} · Task: {task?.status?.replaceAll('_', ' ')}</p></section>;
}
